image: bchabord/flutter-android-docker:latest

stages:
  - build

build_apk:
  stage: build
  script:
    - flutter channel stable
    - flutter upgrade
    - flutter build apk
  artifacts:
    paths:
    - build/app/outputs/apk
