name: copyclient_rx
description: Yet another reactive copyclient rewrite

version: 1.0.0-rc2+22

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  barcode_scan: ^1.0.0
  blocs_copyclient:
    git: https://git.uni-paderborn.de/asta/blocs_copyclient.git
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^0.7.0
  http: ^0.12.0+1
  logging: ^0.11.3+2
  bloc: ^0.9.3
  file_picker: ^1.2.0
  package_info: ^0.4.0+1
  after_layout: ^1.0.7
  sqflite: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/icon_hires.png
    - images/drawer/screen.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
