name: copyclient_rx
description: Yet another reactive copyclient rewrite

version: 1.0.6+60

environment:
  sdk: ">=2.3.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan:
    git: https://github.com/astaupb/flutter_barcode_reader.git
  blocs_copyclient:
    git: https://git.uni-paderborn.de/asta/blocs_copyclient.git
    #path: ../blocs_copyclient/
  #cupertino_icons: ^0.1.2
  flutter_bloc: ^0.19.0
  http: ^0.12.0+2
  logging: ^0.11.3+2
  bloc: ^0.14.4
  file_picker: ^1.3.7
  package_info: ^0.4.0+4
  after_layout: ^1.0.7+2
  sqflite: ^1.1.6+1
  path_provider: ^1.1.2
  permission_handler: ^3.1.0
  bubble_bottom_bar: ^1.2.0
  flutter_webview_plugin: ^0.3.5
  esys_flutter_share: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - images/icon_hires.png
    - images/drawer/screen.jpeg

  fonts:
    - family:  UserAgentIcons
      fonts:
        - asset: fonts/UserAgentIcons.ttf
