name: copyclient_rx
description: Official AStA Copyservice app using the AStAPrint backend
publish_to: none
version: 2.0.1+91

environment:
  sdk: ">=2.3.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^3.0.1
  blocs_copyclient:
    git: https://git.uni-paderborn.de/asta/blocs_copyclient.git
    #version: ^1.1.0
    #path: ../blocs_copyclient/
  flutter_bloc: ^7.0.1
  http: ^0.13.3
  logging: ^1.0.1
  bloc: ^7.0.0
  file_picker: ^3.0.3
  package_info: ^2.0.2
  after_layout: ^1.1.0
  sqflite: ^2.0.0+3
  path_provider: ^1.1.0
  permission_handler: ^8.1.3
  flutter_webview_plugin: ^0.4.0
  esys_flutter_share: ^1.0.2
  receive_sharing_intent:
    git: https://github.com/leontappe/receive_sharing_intent.git
    #path: ../receive_sharing_intent/
  mime: ^1.0.0
  flutter_slidable: ^0.6.0
  universal_html: ^2.0.8

dev_dependencies:
  pedantic: ^1.9.0

flutter:
  uses-material-design: true

  assets:
    - images/icon_hires.png
    - images/drawer/screen.jpeg

  fonts:
    - family:  UserAgentIcons
      fonts:
        - asset: fonts/UserAgentIcons.ttf
