name: copyclient_rx
description: Official AStA Copyservice app using the AStAPrint backend

version: 1.2.0+81

environment:
  sdk: ">=2.3.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^1.0.0
    #git: https://github.com/astaupb/flutter_barcode_reader.git
  blocs_copyclient:
    version: ^1.0.2
    git: https://git.uni-paderborn.de/asta/blocs_copyclient.git
    #path: ../blocs_copyclient/
  flutter_bloc: ^2.0.0
  http: ^0.12.0+2
  logging: ^0.11.3+2
  bloc: ^2.0.0
  file_picker: ^1.4.2
  package_info: ^0.4.0+10
  after_layout: ^1.0.7+2
  sqflite: ^1.1.7+2
  path_provider: ^1.4.0
  permission_handler: ^4.0.0
  flutter_webview_plugin: ^0.3.8
  esys_flutter_share: ^1.0.2
  receive_sharing_intent:
    git: https://github.com/leontappe/receive_sharing_intent.git
    #path: ../receive_sharing_intent/
  mime: ^0.9.6+3

flutter:
  uses-material-design: true

  assets:
    - images/icon_hires.png
    - images/drawer/screen.jpeg

  fonts:
    - family:  UserAgentIcons
      fonts:
        - asset: fonts/UserAgentIcons.ttf
