/// Flutter icons UserAgentIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UserAgentIcons
///      fonts:
///       - asset: fonts/UserAgentIcons.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class UserAgentIcons {
  UserAgentIcons._();

  static const _kFontFam = 'UserAgentIcons';

  static const IconData curl_symbol = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData safari = IconData(0xf267, fontFamily: _kFontFam);
  static const IconData chrome = IconData(0xf268, fontFamily: _kFontFam);
  static const IconData firefox = IconData(0xf269, fontFamily: _kFontFam);
}
